// src/components/Hero.jsx
import { memo, useState, useEffect, Suspense, lazy } from 'react';
import { motion } from 'framer-motion';
import { Canvas } from '@react-three/fiber';

const ParticleField = lazy(() => import('../three/ParticleField.jsx'));
const CrescentStar = lazy(() => import('../three/CrescentStar.jsx'));

const bismillah = 'بِسْمِ ٱللَّٰهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ';

function Hero() {
  const [showCanvas, setShowCanvas] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const mobile = window.innerWidth < 768;
    setIsMobile(mobile);
    setShowCanvas(true);
  }, []);

  return (
    <section
      id="hero"
      className="relative min-h-screen flex items-center justify-center overflow-hidden islamic-pattern-bg"
    >
      {/* 3D Canvas */}
      {showCanvas && (
        <div
          className="absolute inset-0 z-0"
          style={{ pointerEvents: 'none' }}
          aria-hidden="true"
        >
          <Canvas camera={{ position: [0, 0, 5], fov: 60 }}>
            <Suspense fallback={null}>
              <ParticleField count={isMobile ? 500 : 3000} />
              {/* <CrescentStar /> */}
            </Suspense>
          </Canvas>
        </div>
      )}

      {/* Static SVG fallback for mobile */}
      {/* {(
        <div className="absolute inset-0 z-0 flex items-center justify-center opacity-20" aria-hidden="true">
          <svg viewBox="0 0 200 200" className="w-64 h-64" fill="none">
            <circle cx="90" cy="100" r="60" stroke="var(--color-accent)" strokeWidth="2" />
            <circle cx="110" cy="100" r="50" fill="var(--color-bg)" stroke="var(--color-bg)" strokeWidth="2" />
            <polygon
              points="150,65 156,82 174,82 160,93 165,110 150,100 135,110 140,93 126,82 144,82"
              fill="var(--color-accent)"
            />
          </svg>
        </div>
      )} */}

      {/* Content overlay */}
      <div className="relative z-10 text-center px-4 max-w-4xl mx-auto">
        {/* Bismillah */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5, duration: 0.8 }}
          className="mb-8"
          dir="rtl"
        >
          <span className="font-arabic text-2xl md:text-4xl" style={{ color: 'var(--color-accent)' }}>
            {bismillah}
          </span>
        </motion.div>

        {/* Names */}
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 1.2, duration: 0.8, ease: 'easeOut' }}
          className="mb-6"
        >
          <h1
            className="font-display italic font-light leading-tight"
            style={{
              fontSize: 'clamp(2rem, 6vw, 5rem)',
              color: 'var(--color-text)',
            }}
          >
            Tarish Ahmed B
          </h1>
          <span
            className="inline-block my-2 text-xl md:text-2xl"
            style={{ color: 'var(--color-accent)' }}
          >
            ♦
          </span>
          <h1
            className="font-display italic font-light leading-tight"
            style={{
              fontSize: 'clamp(2rem, 6vw, 5rem)',
              color: 'var(--color-text)',
            }}
          >
            Zujaja K
          </h1>
        </motion.div>

        {/* Subtitle */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.8, duration: 0.8 }}
          className="font-display tracking-widest uppercase text-sm md:text-lg"
          style={{ color: 'var(--color-accent)' }}
        >
          Walima ul-Urs
        </motion.p>

        {/* Scroll indicator */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 2.5, duration: 0.8 }}
          className="mt-16 scroll-bounce"
        >
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="var(--color-accent)"
            strokeWidth="2"
            className="mx-auto"
          >
            <polyline points="6 9 12 15 18 9" />
          </svg>
        </motion.div>
      </div>
    </section>
  );
}

export default memo(Hero);

// src/components/Hero.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import { gsap } from 'gsap';
import * as THREE from 'three';

const bismillah = 'بِسْمِ ٱللَّٰهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ';

const canvasContainer = ref(null);
const bismillahRef = ref(null);
const namesRef = ref(null);
const subtitleRef = ref(null);
const scrollRef = ref(null);

let renderer, scene, camera, particles, speeds, particleCount, animFrameId;

function initThree() {
  if (!canvasContainer.value) return;
  const isMobile = window.innerWidth < 768;
  particleCount = isMobile ? 500 : 3000;

  scene = new THREE.Scene();
  const w = canvasContainer.value.clientWidth;
  const h = canvasContainer.value.clientHeight;
  camera = new THREE.PerspectiveCamera(60, w / h, 0.1, 100);
  camera.position.set(0, 0, 5);

  renderer = new THREE.WebGLRenderer({ alpha: true, antialias: false });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setSize(w, h);
  canvasContainer.value.appendChild(renderer.domElement);

  const positions = new Float32Array(particleCount * 3);
  speeds = new Float32Array(particleCount);
  for (let i = 0; i < particleCount; i++) {
    positions[i * 3] = (Math.random() - 0.5) * 20;
    positions[i * 3 + 1] = (Math.random() - 0.5) * 20;
    positions[i * 3 + 2] = (Math.random() - 0.5) * 10;
    speeds[i] = 0.002 + Math.random() * 0.008;
  }

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  const material = new THREE.PointsMaterial({
    size: 0.02,
    color: '#C9A84C',
    transparent: true,
    opacity: 0.8,
    sizeAttenuation: true,
    depthWrite: false,
  });

  particles = new THREE.Points(geometry, material);
  scene.add(particles);

  const animate = () => {
    animFrameId = requestAnimationFrame(animate);
    const pos = particles.geometry.attributes.position.array;
    for (let i = 0; i < particleCount; i++) {
      pos[i * 3 + 1] += speeds[i];
      if (pos[i * 3 + 1] > 10) pos[i * 3 + 1] = -10;
    }
    particles.geometry.attributes.position.needsUpdate = true;
    renderer.render(scene, camera);
  };
  animate();
}

function handleResize() {
  if (!canvasContainer.value || !renderer) return;
  const w = canvasContainer.value.clientWidth;
  const h = canvasContainer.value.clientHeight;
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
  renderer.setSize(w, h);
}

onMounted(() => {
  initThree();
  window.addEventListener('resize', handleResize);
  gsap.fromTo(bismillahRef.value, { opacity: 0, y: 10 }, { opacity: 1, y: 0, delay: 0.5, duration: 0.8 });
  gsap.fromTo(namesRef.value, { opacity: 0, scale: 0.8 }, { opacity: 1, scale: 1, delay: 1.2, duration: 0.8, ease: 'power2.out' });
  gsap.fromTo(subtitleRef.value, { opacity: 0 }, { opacity: 1, delay: 1.8, duration: 0.8 });
  gsap.fromTo(scrollRef.value, { opacity: 0 }, { opacity: 1, delay: 2.5, duration: 0.8 });
});

onUnmounted(() => {
  cancelAnimationFrame(animFrameId);
  window.removeEventListener('resize', handleResize);
  if (renderer) {
    renderer.dispose();
    renderer.domElement.remove();
  }
});
</script>

<template>
  <section
    id="hero"
    class="relative min-h-screen flex items-center justify-center overflow-hidden islamic-pattern-bg"
  >
    <!-- 3D Particle Canvas -->
    <div
      ref="canvasContainer"
      class="absolute inset-0 z-0"
      style="pointer-events: none"
      aria-hidden="true"
    />

    <!-- Content overlay -->
    <div class="relative z-10 text-center px-4 max-w-4xl mx-auto">
      <!-- Bismillah -->
      <div ref="bismillahRef" class="mb-8" style="opacity: 0" dir="rtl">
        <span class="font-arabic text-2xl md:text-4xl" style="color: var(--color-accent)">
          {{ bismillah }}
        </span>
      </div>

      <!-- Names -->
      <div ref="namesRef" class="mb-6" style="opacity: 0">
        <h1
          class="font-display italic font-light leading-tight"
          style="font-size: clamp(2rem, 6vw, 5rem); color: var(--color-text)"
        >
          Tarish Ahmed B
        </h1>
        <span class="inline-block my-2 text-xl md:text-2xl" style="color: var(--color-accent)">♦</span>
        <h1
          class="font-display italic font-light leading-tight"
          style="font-size: clamp(2rem, 6vw, 5rem); color: var(--color-text)"
        >
          Zujaja K
        </h1>
      </div>

      <!-- Subtitle -->
      <p
        ref="subtitleRef"
        class="font-display tracking-widest uppercase text-sm md:text-lg"
        style="color: var(--color-accent); opacity: 0"
      >
        Walima ul-Urs
      </p>

      <!-- Scroll indicator -->
      <div ref="scrollRef" class="mt-16 scroll-bounce" style="opacity: 0">
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="var(--color-accent)"
          stroke-width="2"
          class="mx-auto"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </div>
    </div>
  </section>
</template>
