// src/App.jsx
import Hero from './components/Hero.jsx';
import Invitation from './components/Invitation.jsx';
import EventDetails from './components/EventDetails.jsx';
import Countdown from './components/Countdown.jsx';
import Gallery from './components/Gallery.jsx';
import VenueMap from './components/VenueMap.jsx';
import RSVPForm from './components/RSVPForm.jsx';
import Footer from './components/Footer.jsx';

export default function App() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--color-bg)' }}>
      <Hero />
      <Invitation />
      <EventDetails />
      <Countdown />
      {/* <Gallery /> */}
      <VenueMap />
      <RSVPForm />
      <Footer />
    </div>
  );
}

// src/App.vue
<script setup>
import Hero from './components/Hero.vue';
import Invitation from './components/Invitation.vue';
import EventDetails from './components/EventDetails.vue';
import Countdown from './components/Countdown.vue';
import VenueMap from './components/VenueMap.vue';
import RSVPForm from './components/RSVPForm.vue';
import Footer from './components/Footer.vue';
import RingsScene from './components/RingsScene.vue';
</script>

<template>
  <div class="min-h-screen" style="background-color: var(--color-bg)">
    <Hero />
    <Invitation />
    <EventDetails />
    <Countdown />
    <VenueMap />
    <RSVPForm />
    <Footer />
  </div>
</template>
